& {
    $repoRoot = $(git rev-parse --show-toplevel) -replace "/", "\"

    # Purple theme
    python $repoRoot\local\local_render\local_render.py -d -t 19:34 --publish --custom-theme '{"axis_label_color": "#d8b9ff", "background_color": "#1a0f2e", "cheap_price_color": "#2d3d5a", "fill_alpha": 0.2, "fill_color": "#9d7cff", "grid_alpha": 0.4, "grid_color": "#3d2f50", "label_color": "#f0e6ff", "label_color_avg": "#ffb347", "label_color_max": "#ff6b9d", "label_color_min": "#7cffb3", "label_stroke": true, "nowline_alpha": 0.6, "nowline_color": "#ff6b9d", "plot_linewidth": 1.2, "price_line_color": "#9d7cff", "price_line_color_above_avg": "#ff6b9d", "price_line_color_below_avg": "#9d7cff", "price_line_color_near_avg": "#ffb347", "spine_color": "#503d70", "tick_color": "#d8b9ff", "tickline_color": "#2e1f45", "avgline_color": "#ff6b9d", "avgline_style": ":", "cheapline_color": "#7cffb3", "cheapline_style": ":"}'
    cp $repoRoot\local\local_render\local_render.png $repoRoot\docs\assets\theme-purple.png

    # High contrast theme
    python $repoRoot\local\local_render\local_render.py -d -t 19:34 --publish --custom-theme '{"axis_label_color": "#ffffff", "background_color": "#000000", "cheap_price_color": "#004d00", "fill_alpha": 0.3, "fill_color": "#00ff00", "grid_alpha": 0.6, "grid_color": "#404040", "label_color": "#ffffff", "label_color_avg": "#ffff00", "label_color_max": "#ff0000", "label_color_min": "#00ff00", "label_stroke": true, "nowline_alpha": 0.8, "nowline_color": "#ff00ff", "plot_linewidth": 2.0, "price_line_color": "#00ff00", "price_line_color_above_avg": "#ff0000", "price_line_color_below_avg": "#00ff00", "price_line_color_near_avg": "#ffff00", "spine_color": "#808080", "tick_color": "#ffffff", "tickline_color": "#404040", "avgline_color": "#ff0000", "avgline_style": ":", "cheapline_color": "#00ff00", "cheapline_style": ":"}'
    cp $repoRoot\local\local_render\local_render.png $repoRoot\docs\assets\theme-contrast.png

    # Warm amber theme
    python $repoRoot\local\local_render\local_render.py -d -t 19:34 --publish --custom-theme '{"axis_label_color": "#ffd89b", "background_color": "#2c1810", "cheap_price_color": "#4d3b1f", "fill_alpha": 0.25, "fill_color": "#ff9a56", "grid_alpha": 0.35, "grid_color": "#4d3020", "label_color": "#ffe4c4", "label_color_avg": "#ffd700", "label_color_max": "#ff6347", "label_color_min": "#98fb98", "label_stroke": true, "nowline_alpha": 0.6, "nowline_color": "#ff8c00", "plot_linewidth": 1.2, "price_line_color": "#ff9a56", "price_line_color_above_avg": "#ff6347", "price_line_color_below_avg": "#ff9a56", "price_line_color_near_avg": "#ffd700", "spine_color": "#5d4030", "tick_color": "#ffd89b", "tickline_color": "#3d2820", "avgline_color": "#ff6347", "avgline_style": ":", "cheapline_color": "#98fb98", "cheapline_style": ":"}'
    cp $repoRoot\local\local_render\local_render.png $repoRoot\docs\assets\theme-amber.png

    # Cool blue-green theme
    python $repoRoot\local\local_render\local_render.py -d -t 19:34 --publish --custom-theme '{"axis_label_color": "#a8d8ea", "background_color": "#0a1929", "cheap_price_color": "#1a4d4d", "fill_alpha": 0.22, "fill_color": "#4dd0e1", "grid_alpha": 0.4, "grid_color": "#1e3a5f", "label_color": "#e0f7fa", "label_color_avg": "#ffd54f", "label_color_max": "#ff80ab", "label_color_min": "#69f0ae", "label_stroke": true, "nowline_alpha": 0.55, "nowline_color": "#ff6e40", "plot_linewidth": 1.1, "price_line_color": "#4dd0e1", "price_line_color_above_avg": "#ff80ab", "price_line_color_below_avg": "#4dd0e1", "price_line_color_near_avg": "#ffd54f", "spine_color": "#2e4a6f", "tick_color": "#a8d8ea", "tickline_color": "#152a3f", "avgline_color": "#ff80ab", "avgline_style": ":", "cheapline_color": "#69f0ae", "cheapline_style": ":"}'
    cp $repoRoot\local\local_render\local_render.png $repoRoot\docs\assets\theme-bluegreen.png

    # Red theme
    python $repoRoot\local\local_render\local_render.py -d -t 19:34 --publish --custom-theme '{"axis_label_color": "#ffcccc", "background_color": "#330000", "cheap_price_color": "#660000", "fill_alpha": 0.25, "fill_color": "#ff6666", "grid_alpha": 0.4, "grid_color": "#660000", "label_color": "#ffcccc", "label_color_avg": "#ffaa00", "label_color_max": "#ff0000", "label_color_min": "#66ff66", "label_stroke": true, "nowline_alpha": 0.7, "nowline_color": "#ffff00", "plot_linewidth": 1.5, "price_line_color": "#ff6666", "price_line_color_above_avg": "#ff0000", "price_line_color_below_avg": "#ff9999", "price_line_color_near_avg": "#ffaa00", "spine_color": "#990000", "tick_color": "#ffcccc", "tickline_color": "#440000", "avgline_color": "#ff0000", "avgline_style": ":", "cheapline_color": "#66ff66", "cheapline_style": ":"}'
    cp $repoRoot\local\local_render\local_render.png $repoRoot\docs\assets\theme-red.png
}
