"""Constants for the Tibber Graph integration."""

# Import default values from defaults.py
# All settings are configurable via UI except theme colors (in themes.json) and interval settings
from .defaults import (
    # General settings
    THEME,
    TRANSPARENT_BACKGROUND,
    CANVAS_WIDTH,
    CANVAS_HEIGHT,
    FORCE_FIXED_SIZE,
    LABEL_FONT_SIZE,
    START_GRAPH_AT,
    HOURS_TO_SHOW,
    CHEAP_PRICE_POINTS,
    CHEAP_PRICE_THRESHOLD,
    SHOW_AVERAGE_PRICE_LINE,
    SHOW_CHEAP_PRICE_LINE,
    COLOR_PRICE_LINE_BY_AVERAGE,
    BOTTOM_MARGIN,
    LEFT_MARGIN,
    NEAR_AVERAGE_THRESHOLD,
    COLOR_GRADIENT_INTERPOLATION_STEPS,
    # Price labels
    PRICE_DECIMALS,
    USE_HOURLY_PRICES,
    USE_CENTS,
    CURRENCY_OVERRIDE,
    LABEL_SHOW_CURRENCY,
    LABEL_CURRENT,
    LABEL_CURRENT_IN_HEADER_FONT_WEIGHT,
    LABEL_CURRENT_IN_HEADER_PADDING,
    LABEL_FONT_WEIGHT,
    LABEL_MIN,
    LABEL_MAX,
    LABEL_USE_COLORS,
    LABEL_MINMAX_PER_DAY,
    # X-axis settings
    SHOW_X_AXIS,
    X_TICK_STEP_HOURS,
    CHEAP_PERIODS_ON_X_AXIS,
    SHOW_VERTICAL_GRID,
    X_AXIS_LABEL_Y_OFFSET,
    CHEAP_BOUNDARY_HIGHLIGHT,
    # Y-axis settings
    SHOW_Y_AXIS,
    Y_TICK_COUNT,
    Y_AXIS_LABEL_ROTATION_DEG,
    Y_AXIS_SIDE,
    Y_TICK_USE_COLORS,
    SHOW_HORIZONTAL_GRID,
    Y_AXIS_LABEL_VERTICAL_ANCHOR,
    # Refresh settings
    REFRESH_MODE,
    MIN_REDRAW_INTERVAL_SECONDS,
    RENDER_STAGGER_MAX_SECONDS,
    REFRESH_INTERVAL_DELAY_SECONDS,
    # Footer settings
    SHOW_DATA_SOURCE_NAME,
    DATA_SOURCE_NAME_FONT_SIZE_DIFF,
)

DOMAIN = "tibber_graph"

# Config entry keys
CONF_ENTITY_NAME = "entity_name"
CONF_PRICE_ENTITY_ID = "price_entity_id"
CONF_CUSTOM_THEME = "custom_theme"
# Custom data source config keys
CONF_DATA_ATTR = "data_attr"
CONF_DATA_ATTR_START_FIELD = "data_attr_start_field"
CONF_DATA_ATTR_START_FMT = "data_attr_start_fmt"
CONF_DATA_ATTR_PRICE_FIELD = "data_attr_price_field"
CONF_DATA_ATTR_PRICE_FACTOR = "data_attr_price_factor"
CONF_DATA_ATTR_PRICE_ADD = "data_attr_price_add"
CONF_CURRENCY_ATTR = "currency_attr"
# General settings
CONF_THEME = "theme"
CONF_TRANSPARENT_BACKGROUND = "transparent_background"
CONF_CANVAS_WIDTH = "canvas_width"
CONF_CANVAS_HEIGHT = "canvas_height"
CONF_FORCE_FIXED_SIZE = "force_fixed_size"
CONF_LABEL_FONT_SIZE = "label_font_size"
CONF_START_GRAPH_AT = "start_graph_at"
CONF_HOURS_TO_SHOW = "hours_to_show"
CONF_CHEAP_PRICE_POINTS = "cheap_price_points"
CONF_CHEAP_PRICE_THRESHOLD = "cheap_price_threshold"
CONF_SHOW_AVERAGE_PRICE_LINE = "show_average_price_line"
CONF_SHOW_CHEAP_PRICE_LINE = "show_cheap_price_line"
CONF_COLOR_PRICE_LINE_BY_AVERAGE = "color_price_line_by_average"
# Price labels
CONF_PRICE_DECIMALS = "price_decimals"
CONF_USE_HOURLY_PRICES = "use_hourly_prices"
CONF_USE_CENTS = "use_cents"
CONF_CURRENCY_OVERRIDE = "currency_override"
CONF_LABEL_SHOW_CURRENCY = "label_show_currency"
CONF_LABEL_CURRENT = "label_current"
CONF_LABEL_MIN = "label_min"
CONF_LABEL_MAX = "label_max"
CONF_LABEL_USE_COLORS = "label_use_colors"
CONF_LABEL_MINMAX_PER_DAY = "label_minmax_per_day"
# X-axis settings
CONF_SHOW_X_AXIS = "show_x_axis"
CONF_X_TICK_STEP_HOURS = "x_tick_step_hours"
CONF_CHEAP_PERIODS_ON_X_AXIS = "cheap_periods_on_x_axis"
CONF_SHOW_VERTICAL_GRID = "show_vertical_grid"
CONF_CHEAP_BOUNDARY_HIGHLIGHT = "cheap_boundary_highlight"
# Y-axis settings
CONF_SHOW_Y_AXIS = "show_y_axis"
CONF_Y_TICK_COUNT = "y_tick_count"
CONF_Y_AXIS_LABEL_ROTATION_DEG = "y_axis_label_rotation_deg"
CONF_Y_AXIS_SIDE = "y_axis_side"
CONF_Y_TICK_USE_COLORS = "y_tick_use_colors"
CONF_SHOW_HORIZONTAL_GRID = "show_horizontal_grid"
# Refresh settings
CONF_REFRESH_MODE = "refresh_mode"
# Footer settings
CONF_SHOW_DATA_SOURCE_NAME = "show_data_source_name"

# Refresh mode options
REFRESH_MODE_SYSTEM = "system"
REFRESH_MODE_SYSTEM_INTERVAL = "system_interval"
REFRESH_MODE_INTERVAL = "interval"
REFRESH_MODE_SENSOR = "sensor"
REFRESH_MODE_MANUAL = "manual"

# Default values imported from defaults.py
DEFAULT_ENTITY_NAME = None  # Will be auto-generated if not provided
DEFAULT_PRICE_ENTITY_ID = None  # Optional - if not provided, use Tibber integration
# Custom data source defaults - None means use default detection from SUPPORTED_* lists
DEFAULT_DATA_ATTR = None
DEFAULT_DATA_ATTR_START_FIELD = None
DEFAULT_DATA_ATTR_START_FMT = None
DEFAULT_DATA_ATTR_PRICE_FIELD = None
DEFAULT_DATA_ATTR_PRICE_FACTOR = None
DEFAULT_DATA_ATTR_PRICE_ADD = None
DEFAULT_CURRENCY_ATTR = None
# General settings
DEFAULT_THEME = THEME
DEFAULT_TRANSPARENT_BACKGROUND = TRANSPARENT_BACKGROUND
DEFAULT_CANVAS_WIDTH = CANVAS_WIDTH
DEFAULT_CANVAS_HEIGHT = CANVAS_HEIGHT
DEFAULT_FORCE_FIXED_SIZE = FORCE_FIXED_SIZE
DEFAULT_LABEL_FONT_SIZE = LABEL_FONT_SIZE
DEFAULT_START_GRAPH_AT = START_GRAPH_AT
DEFAULT_HOURS_TO_SHOW = HOURS_TO_SHOW
DEFAULT_CHEAP_PRICE_POINTS = CHEAP_PRICE_POINTS
DEFAULT_CHEAP_PRICE_THRESHOLD = CHEAP_PRICE_THRESHOLD
DEFAULT_SHOW_AVERAGE_PRICE_LINE = SHOW_AVERAGE_PRICE_LINE
DEFAULT_SHOW_CHEAP_PRICE_LINE = SHOW_CHEAP_PRICE_LINE
DEFAULT_COLOR_PRICE_LINE_BY_AVERAGE = COLOR_PRICE_LINE_BY_AVERAGE
DEFAULT_BOTTOM_MARGIN = BOTTOM_MARGIN
DEFAULT_LEFT_MARGIN = LEFT_MARGIN
DEFAULT_NEAR_AVERAGE_THRESHOLD = NEAR_AVERAGE_THRESHOLD
DEFAULT_COLOR_GRADIENT_INTERPOLATION_STEPS = COLOR_GRADIENT_INTERPOLATION_STEPS
# Price labels
DEFAULT_PRICE_DECIMALS = PRICE_DECIMALS
DEFAULT_USE_HOURLY_PRICES = USE_HOURLY_PRICES
DEFAULT_USE_CENTS = USE_CENTS
DEFAULT_CURRENCY_OVERRIDE = CURRENCY_OVERRIDE
DEFAULT_LABEL_SHOW_CURRENCY = LABEL_SHOW_CURRENCY
DEFAULT_LABEL_CURRENT = LABEL_CURRENT
DEFAULT_LABEL_CURRENT_IN_HEADER_FONT_WEIGHT = LABEL_CURRENT_IN_HEADER_FONT_WEIGHT
DEFAULT_LABEL_CURRENT_IN_HEADER_PADDING = LABEL_CURRENT_IN_HEADER_PADDING
DEFAULT_LABEL_FONT_WEIGHT = LABEL_FONT_WEIGHT
DEFAULT_LABEL_MIN = LABEL_MIN
DEFAULT_LABEL_MAX = LABEL_MAX
DEFAULT_LABEL_USE_COLORS = LABEL_USE_COLORS
DEFAULT_LABEL_MINMAX_PER_DAY = LABEL_MINMAX_PER_DAY
# X-axis settings
DEFAULT_SHOW_X_AXIS = SHOW_X_AXIS
DEFAULT_X_TICK_STEP_HOURS = X_TICK_STEP_HOURS
DEFAULT_CHEAP_PERIODS_ON_X_AXIS = CHEAP_PERIODS_ON_X_AXIS
DEFAULT_SHOW_VERTICAL_GRID = SHOW_VERTICAL_GRID
DEFAULT_X_AXIS_LABEL_Y_OFFSET = X_AXIS_LABEL_Y_OFFSET
DEFAULT_CHEAP_BOUNDARY_HIGHLIGHT = CHEAP_BOUNDARY_HIGHLIGHT
# Y-axis settings
DEFAULT_SHOW_Y_AXIS = SHOW_Y_AXIS
DEFAULT_Y_TICK_COUNT = Y_TICK_COUNT
DEFAULT_Y_AXIS_LABEL_ROTATION_DEG = Y_AXIS_LABEL_ROTATION_DEG
DEFAULT_Y_AXIS_SIDE = Y_AXIS_SIDE
DEFAULT_Y_TICK_USE_COLORS = Y_TICK_USE_COLORS
DEFAULT_SHOW_HORIZONTAL_GRID = SHOW_HORIZONTAL_GRID
DEFAULT_Y_AXIS_LABEL_VERTICAL_ANCHOR = Y_AXIS_LABEL_VERTICAL_ANCHOR
# Refresh settings
DEFAULT_REFRESH_MODE = REFRESH_MODE
DEFAULT_MIN_REDRAW_INTERVAL_SECONDS = MIN_REDRAW_INTERVAL_SECONDS
DEFAULT_RENDER_STAGGER_MAX_SECONDS = RENDER_STAGGER_MAX_SECONDS
DEFAULT_REFRESH_INTERVAL_DELAY_SECONDS = REFRESH_INTERVAL_DELAY_SECONDS
# Footer settings
DEFAULT_SHOW_DATA_SOURCE_NAME = SHOW_DATA_SOURCE_NAME
DEFAULT_DATA_SOURCE_NAME_FONT_SIZE_DIFF = DATA_SOURCE_NAME_FONT_SIZE_DIFF

# Start graph at options
START_GRAPH_AT_MIDNIGHT = "midnight"
START_GRAPH_AT_CURRENT_HOUR = "current_hour"
START_GRAPH_AT_SHOW_ALL = "show_all"

# Label current options
LABEL_CURRENT_ON = "on"
LABEL_CURRENT_ON_CURRENT_PRICE_ONLY = "on_current_price_only"
LABEL_CURRENT_ON_IN_GRAPH = "on_in_graph"
LABEL_CURRENT_ON_IN_GRAPH_NO_PRICE = "on_in_graph_no_price"
LABEL_CURRENT_ON_IN_GRAPH_NO_TIME = "on_in_graph_no_time"
LABEL_CURRENT_ON_IN_GRAPH_ONLY_MARKER = "on_in_graph_only_marker"
LABEL_CURRENT_OFF = "off"

# Show X-axis options
SHOW_X_AXIS_ON = "on"
SHOW_X_AXIS_ON_WITH_TICK_MARKS = "on_with_tick_marks"
SHOW_X_AXIS_OFF = "off"

# Show Y-axis options
SHOW_Y_AXIS_ON = "on"
SHOW_Y_AXIS_ON_WITH_TICK_MARKS = "on_with_tick_marks"
SHOW_Y_AXIS_OFF = "off"

# Label max/min options
LABEL_MAX_ON = "on"
LABEL_MAX_ON_NO_PRICE = "on_no_price"
LABEL_MAX_ON_NO_TIME = "on_no_time"
LABEL_MAX_ON_ONLY_MARKER = "on_only_marker"
LABEL_MAX_OFF = "off"

LABEL_MIN_ON = "on"
LABEL_MIN_ON_NO_PRICE = "on_no_price"
LABEL_MIN_ON_NO_TIME = "on_no_time"
LABEL_MIN_ON_ONLY_MARKER = "on_only_marker"
LABEL_MIN_OFF = "off"

# Cheap periods on X-axis options
CHEAP_PERIODS_ON_X_AXIS_ON = "on"
CHEAP_PERIODS_ON_X_AXIS_ON_COMFY = "on_comfy"
CHEAP_PERIODS_ON_X_AXIS_ON_COMPACT = "on_compact"
CHEAP_PERIODS_ON_X_AXIS_OFF = "off"

# Cheap boundary highlight options
CHEAP_BOUNDARY_HIGHLIGHT_NONE = "none"
CHEAP_BOUNDARY_HIGHLIGHT_UNDERLINE = "underline"
CHEAP_BOUNDARY_HIGHLIGHT_UNDERLINE_ALL = "underline_all"

# Y-axis side options
Y_AXIS_SIDE_LEFT = "left"
Y_AXIS_SIDE_RIGHT = "right"

# External domain constants
SENSOR_DOMAIN = "sensor"
TIBBER_DOMAIN = "tibber"

# Custom data source configuration - supported attribute names (ordered by priority)
SUPPORTED_DATA_ATTRIBUTES = ["prices", "data"]

# Custom data source configuration - supported field names (ordered by priority)
SUPPORTED_START_TIME_FIELDS = ["start_time", "start", "startsAt"]
SUPPORTED_PRICE_FIELDS = ["price", "price_per_kwh", "total"]
