"""Constants for the Tibber Graph integration."""

# Import default values from defaults.py
# All settings are configurable via UI except LIGHT_*/DARK_* theme colors and interval settings
from .defaults import (
    THEME,
    # General settings
    CANVAS_WIDTH,
    CANVAS_HEIGHT,
    FORCE_FIXED_SIZE,
    # X-axis settings
    SHOW_X_TICKS,
    START_AT_MIDNIGHT,
    X_AXIS_LABEL_ROTATION_DEG,
    X_TICK_STEP_HOURS,
    HOURS_TO_SHOW,
    # Y-axis settings
    SHOW_Y_AXIS,
    SHOW_Y_GRID,
    Y_AXIS_LABEL_ROTATION_DEG,
    Y_AXIS_SIDE,
    Y_TICK_COUNT,
    Y_TICK_USE_COLORS,
    # Price labels
    USE_HOURLY_PRICES,
    USE_CENTS,
    CURRENCY_OVERRIDE,
    LABEL_CURRENT,
    LABEL_CURRENT_AT_TOP,
    LABEL_CURRENT_AT_TOP_FONT_WEIGHT,
    LABEL_CURRENT_AT_TOP_PADDING,
    LABEL_FONT_SIZE,
    LABEL_FONT_WEIGHT,
    LABEL_MAX,
    LABEL_MIN,
    LABEL_MINMAX_SHOW_PRICE,
    LABEL_SHOW_CURRENCY,
    LABEL_USE_COLORS,
    PRICE_DECIMALS,
    # Refresh settings
    AUTO_REFRESH_ENABLED,
)

DOMAIN = "tibber_graph"

# Config entry keys
CONF_THEME = "theme"
CONF_CANVAS_WIDTH = "canvas_width"
CONF_CANVAS_HEIGHT = "canvas_height"
CONF_FORCE_FIXED_SIZE = "force_fixed_size"
# X-axis
CONF_SHOW_X_TICKS = "show_x_ticks"
CONF_START_AT_MIDNIGHT = "start_at_midnight"
CONF_X_AXIS_LABEL_ROTATION_DEG = "x_axis_label_rotation_deg"
CONF_X_TICK_STEP_HOURS = "x_tick_step_hours"
CONF_HOURS_TO_SHOW = "hours_to_show"
# Y-axis
CONF_SHOW_Y_AXIS = "show_y_axis"
CONF_SHOW_Y_GRID = "show_y_grid"
CONF_Y_AXIS_LABEL_ROTATION_DEG = "y_axis_label_rotation_deg"
CONF_Y_AXIS_SIDE = "y_axis_side"
CONF_Y_TICK_COUNT = "y_tick_count"
CONF_Y_TICK_USE_COLORS = "y_tick_use_colors"
# Price labels
CONF_USE_HOURLY_PRICES = "use_hourly_prices"
CONF_USE_CENTS = "use_cents"
CONF_CURRENCY_OVERRIDE = "currency_override"
CONF_LABEL_CURRENT = "label_current"
CONF_LABEL_CURRENT_AT_TOP = "label_current_at_top"
CONF_LABEL_FONT_SIZE = "label_font_size"
CONF_LABEL_MAX = "label_max"
CONF_LABEL_MIN = "label_min"
CONF_LABEL_MINMAX_SHOW_PRICE = "label_minmax_show_price"
CONF_LABEL_SHOW_CURRENCY = "label_show_currency"
CONF_LABEL_USE_COLORS = "label_use_colors"
CONF_PRICE_DECIMALS = "price_decimals"
# Refresh
CONF_AUTO_REFRESH_ENABLED = "auto_refresh_enabled"

# Default values imported from defaults.py
DEFAULT_THEME = THEME
DEFAULT_CANVAS_WIDTH = CANVAS_WIDTH
DEFAULT_CANVAS_HEIGHT = CANVAS_HEIGHT
DEFAULT_FORCE_FIXED_SIZE = FORCE_FIXED_SIZE
# X-axis defaults
DEFAULT_SHOW_X_TICKS = SHOW_X_TICKS
DEFAULT_START_AT_MIDNIGHT = START_AT_MIDNIGHT
DEFAULT_X_AXIS_LABEL_ROTATION_DEG = X_AXIS_LABEL_ROTATION_DEG
DEFAULT_X_TICK_STEP_HOURS = X_TICK_STEP_HOURS
DEFAULT_HOURS_TO_SHOW = HOURS_TO_SHOW
# Y-axis defaults
DEFAULT_SHOW_Y_AXIS = SHOW_Y_AXIS
DEFAULT_SHOW_Y_GRID = SHOW_Y_GRID
DEFAULT_Y_AXIS_LABEL_ROTATION_DEG = Y_AXIS_LABEL_ROTATION_DEG
DEFAULT_Y_AXIS_SIDE = Y_AXIS_SIDE
DEFAULT_Y_TICK_COUNT = Y_TICK_COUNT
DEFAULT_Y_TICK_USE_COLORS = Y_TICK_USE_COLORS
# Price label defaults
DEFAULT_USE_HOURLY_PRICES = USE_HOURLY_PRICES
DEFAULT_USE_CENTS = USE_CENTS
DEFAULT_CURRENCY_OVERRIDE = CURRENCY_OVERRIDE
DEFAULT_LABEL_CURRENT = LABEL_CURRENT
DEFAULT_LABEL_CURRENT_AT_TOP = LABEL_CURRENT_AT_TOP
DEFAULT_LABEL_FONT_SIZE = LABEL_FONT_SIZE
DEFAULT_LABEL_MAX = LABEL_MAX
DEFAULT_LABEL_MIN = LABEL_MIN
DEFAULT_LABEL_MINMAX_SHOW_PRICE = LABEL_MINMAX_SHOW_PRICE
DEFAULT_LABEL_SHOW_CURRENCY = LABEL_SHOW_CURRENCY
DEFAULT_LABEL_USE_COLORS = LABEL_USE_COLORS
DEFAULT_PRICE_DECIMALS = PRICE_DECIMALS
# Refresh defaults
DEFAULT_AUTO_REFRESH_ENABLED = AUTO_REFRESH_ENABLED
