"""Constants for the Tibber Graph integration."""

# Import default values from defaults.py
# All settings are configurable via UI except theme colors (in themes.json) and interval settings
from .defaults import (
    # General settings
    THEME,
    TRANSPARENT_BACKGROUND,
    CANVAS_WIDTH,
    CANVAS_HEIGHT,
    FORCE_FIXED_SIZE,
    BOTTOM_MARGIN,
    LEFT_MARGIN,
    # X-axis settings
    SHOW_X_TICKS,
    START_GRAPH_AT,
    X_TICK_STEP_HOURS,
    HOURS_TO_SHOW,
    SHOW_VERTICAL_GRID,
    X_AXIS_LABEL_Y_OFFSET,
    # Y-axis settings
    SHOW_Y_AXIS,
    SHOW_Y_AXIS_TICKS,
    SHOW_HORIZONTAL_GRID,
    SHOW_AVERAGE_PRICE_LINE,
    CHEAP_PRICE_POINTS,
    CHEAP_PRICE_THRESHOLD,
    Y_AXIS_LABEL_ROTATION_DEG,
    Y_AXIS_SIDE,
    Y_TICK_COUNT,
    Y_TICK_USE_COLORS,
    Y_AXIS_LABEL_VERTICAL_ANCHOR,
    # Price label settings
    USE_HOURLY_PRICES,
    USE_CENTS,
    CURRENCY_OVERRIDE,
    LABEL_CURRENT,
    LABEL_CURRENT_IN_HEADER,
    LABEL_CURRENT_IN_HEADER_MORE,
    LABEL_CURRENT_IN_HEADER_FONT_WEIGHT,
    LABEL_CURRENT_IN_HEADER_PADDING,
    LABEL_FONT_SIZE,
    LABEL_FONT_WEIGHT,
    LABEL_MAX,
    LABEL_MAX_BELOW_POINT,
    LABEL_MIN,
    LABEL_MINMAX_SHOW_PRICE,
    LABEL_SHOW_CURRENCY,
    LABEL_USE_COLORS,
    PRICE_DECIMALS,
    COLOR_PRICE_LINE_BY_AVERAGE,
    NEAR_AVERAGE_THRESHOLD,
    # Refresh settings
    AUTO_REFRESH_ENABLED,
    AUTO_REFRESH_INTERVAL_MINUTES,
    MIN_REDRAW_INTERVAL_SECONDS,
    RENDER_STAGGER_MAX_SECONDS,
)

DOMAIN = "tibber_graph"

# Config entry keys
CONF_ENTITY_NAME = "entity_name"
CONF_PRICE_ENTITY_ID = "price_entity_id"
# General config keys
CONF_THEME = "theme"
CONF_CUSTOM_THEME = "custom_theme"
CONF_TRANSPARENT_BACKGROUND = "transparent_background"
CONF_CANVAS_WIDTH = "canvas_width"
CONF_CANVAS_HEIGHT = "canvas_height"
CONF_FORCE_FIXED_SIZE = "force_fixed_size"
# X-axis config keys
CONF_SHOW_X_TICKS = "show_x_ticks"
CONF_START_GRAPH_AT = "start_graph_at"
CONF_X_TICK_STEP_HOURS = "x_tick_step_hours"
CONF_HOURS_TO_SHOW = "hours_to_show"
CONF_SHOW_VERTICAL_GRID = "show_vertical_grid"
# Y-axis config keys
CONF_SHOW_Y_AXIS = "show_y_axis"
CONF_SHOW_Y_AXIS_TICKS = "show_y_axis_ticks"
CONF_SHOW_HORIZONTAL_GRID = "show_horizontal_grid"
CONF_SHOW_AVERAGE_PRICE_LINE = "show_average_price_line"
CONF_CHEAP_PRICE_POINTS = "cheap_price_points"
CONF_CHEAP_PRICE_THRESHOLD = "cheap_price_threshold"
CONF_Y_AXIS_LABEL_ROTATION_DEG = "y_axis_label_rotation_deg"
CONF_Y_AXIS_SIDE = "y_axis_side"
CONF_Y_TICK_COUNT = "y_tick_count"
CONF_Y_TICK_USE_COLORS = "y_tick_use_colors"
# Price label config keys
CONF_USE_HOURLY_PRICES = "use_hourly_prices"
CONF_USE_CENTS = "use_cents"
CONF_CURRENCY_OVERRIDE = "currency_override"
CONF_LABEL_CURRENT = "label_current"
CONF_LABEL_CURRENT_IN_HEADER = "label_current_in_header"
CONF_LABEL_CURRENT_IN_HEADER_MORE = "label_current_in_header_more"
CONF_LABEL_FONT_SIZE = "label_font_size"
CONF_LABEL_MAX = "label_max"
CONF_LABEL_MIN = "label_min"
CONF_LABEL_MINMAX_SHOW_PRICE = "label_minmax_show_price"
CONF_LABEL_SHOW_CURRENCY = "label_show_currency"
CONF_LABEL_USE_COLORS = "label_use_colors"
CONF_PRICE_DECIMALS = "price_decimals"
CONF_COLOR_PRICE_LINE_BY_AVERAGE = "color_price_line_by_average"
# Refresh config keys
CONF_AUTO_REFRESH_ENABLED = "auto_refresh_enabled"

# Default values imported from defaults.py
DEFAULT_ENTITY_NAME = None  # Will be auto-generated if not provided
DEFAULT_PRICE_ENTITY_ID = None  # Optional - if not provided, use Tibber integration
# General defaults
DEFAULT_THEME = THEME
DEFAULT_TRANSPARENT_BACKGROUND = TRANSPARENT_BACKGROUND
DEFAULT_CANVAS_WIDTH = CANVAS_WIDTH
DEFAULT_CANVAS_HEIGHT = CANVAS_HEIGHT
DEFAULT_FORCE_FIXED_SIZE = FORCE_FIXED_SIZE
DEFAULT_BOTTOM_MARGIN = BOTTOM_MARGIN
DEFAULT_LEFT_MARGIN = LEFT_MARGIN
# X-axis defaults
DEFAULT_SHOW_X_TICKS = SHOW_X_TICKS
DEFAULT_START_GRAPH_AT = START_GRAPH_AT
DEFAULT_X_TICK_STEP_HOURS = X_TICK_STEP_HOURS
DEFAULT_HOURS_TO_SHOW = HOURS_TO_SHOW
DEFAULT_SHOW_VERTICAL_GRID = SHOW_VERTICAL_GRID
DEFAULT_X_AXIS_LABEL_Y_OFFSET = X_AXIS_LABEL_Y_OFFSET
# Y-axis defaults
DEFAULT_SHOW_Y_AXIS = SHOW_Y_AXIS
DEFAULT_SHOW_Y_AXIS_TICKS = SHOW_Y_AXIS_TICKS
DEFAULT_SHOW_HORIZONTAL_GRID = SHOW_HORIZONTAL_GRID
DEFAULT_SHOW_AVERAGE_PRICE_LINE = SHOW_AVERAGE_PRICE_LINE
DEFAULT_CHEAP_PRICE_POINTS = CHEAP_PRICE_POINTS
DEFAULT_CHEAP_PRICE_THRESHOLD = CHEAP_PRICE_THRESHOLD
DEFAULT_Y_AXIS_LABEL_ROTATION_DEG = Y_AXIS_LABEL_ROTATION_DEG
DEFAULT_Y_AXIS_SIDE = Y_AXIS_SIDE
DEFAULT_Y_TICK_COUNT = Y_TICK_COUNT
DEFAULT_Y_TICK_USE_COLORS = Y_TICK_USE_COLORS
DEFAULT_Y_AXIS_LABEL_VERTICAL_ANCHOR = Y_AXIS_LABEL_VERTICAL_ANCHOR
# Price label defaults
DEFAULT_USE_HOURLY_PRICES = USE_HOURLY_PRICES
DEFAULT_USE_CENTS = USE_CENTS
DEFAULT_CURRENCY_OVERRIDE = CURRENCY_OVERRIDE
DEFAULT_LABEL_CURRENT = LABEL_CURRENT
DEFAULT_LABEL_CURRENT_IN_HEADER = LABEL_CURRENT_IN_HEADER
DEFAULT_LABEL_CURRENT_IN_HEADER_MORE = LABEL_CURRENT_IN_HEADER_MORE
DEFAULT_LABEL_CURRENT_IN_HEADER_FONT_WEIGHT = LABEL_CURRENT_IN_HEADER_FONT_WEIGHT
DEFAULT_LABEL_CURRENT_IN_HEADER_PADDING = LABEL_CURRENT_IN_HEADER_PADDING
DEFAULT_LABEL_FONT_SIZE = LABEL_FONT_SIZE
DEFAULT_LABEL_FONT_WEIGHT = LABEL_FONT_WEIGHT
DEFAULT_LABEL_MAX = LABEL_MAX
DEFAULT_LABEL_MAX_BELOW_POINT = LABEL_MAX_BELOW_POINT
DEFAULT_LABEL_MIN = LABEL_MIN
DEFAULT_LABEL_MINMAX_SHOW_PRICE = LABEL_MINMAX_SHOW_PRICE
DEFAULT_LABEL_SHOW_CURRENCY = LABEL_SHOW_CURRENCY
DEFAULT_LABEL_USE_COLORS = LABEL_USE_COLORS
DEFAULT_PRICE_DECIMALS = PRICE_DECIMALS
DEFAULT_COLOR_PRICE_LINE_BY_AVERAGE = COLOR_PRICE_LINE_BY_AVERAGE
DEFAULT_NEAR_AVERAGE_THRESHOLD = NEAR_AVERAGE_THRESHOLD
# Refresh defaults
DEFAULT_AUTO_REFRESH_ENABLED = AUTO_REFRESH_ENABLED
DEFAULT_AUTO_REFRESH_INTERVAL_MINUTES = AUTO_REFRESH_INTERVAL_MINUTES
DEFAULT_MIN_REDRAW_INTERVAL_SECONDS = MIN_REDRAW_INTERVAL_SECONDS
DEFAULT_RENDER_STAGGER_MAX_SECONDS = RENDER_STAGGER_MAX_SECONDS

# Start graph at options
START_GRAPH_AT_MIDNIGHT = "midnight"
START_GRAPH_AT_CURRENT_HOUR = "current_hour"
START_GRAPH_AT_SHOW_ALL = "show_all"
